services:
  - type: web
    name: games4life-backend
    runtime: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -Dspring.profiles.active=prod -Dserver.port=$PORT -jar target/games4life-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m -Xms256m
