spring.application.name=games4life-backend

# Porta que o Render define automaticamente
server.port=${PORT:8080}

# Banco em mem√≥ria H2
spring.datasource.url=jdbc:h2:mem:usuario;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Server
server.compression.enabled=true
server.compression.min-response-size=1024

# Logging
logging.level.root=INFO
logging.level.com.jogosparavida=INFO
